### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by AndreaCensi**
Clean up trying to understand what it does.

Please review as I didn't try any.

The form gives me an error after the first submit.

### CODE REVIEW

**Comment by AmaurX** [comment]
@AndreaCensi do you use python3 ? Your branch does not crash on my computer with python 3.
@surirohit most of the proposed changes concern your work, can you take a look at it?

**Comment by AndreaCensi** [comment]
@AleksandarPetrov  

Run it with `docker-compose up`.

The logic is broken, it seems. And the forms looks for some undefined variables.

**Comment by AndreaCensi** [comment]
@AmaurX Running with `docker-compose up` avoids all issues of "what version are you running?".

**Comment by AmaurX** [comment]
@surirohit I'd like to merge to master, but I need your review on the aido scripts

**Comment by surirohit** [comment]
@AndreaCensi thank you for the cleanup and review

I changed a small thing with multiprocessing. I had to change `pool.map` to `pool.starmap` to make it work with multiple arguments, but I believe this is what you intended. 

I will also change the os.popen calls as you suggested, but merging first!

**Pull request merged**
